import { readdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import path from "node:path";

// Emits a Netlify `_headers` file (https://docs.netlify.com/routing/headers/)
// with a strict Content-Security-Policy plus the usual hardening headers.
//
// The site is a fully static, no-backend Astro build, so its only real attack
// surface is the browser: a strict CSP is the highest-value control here. The
// tricky part is that the app leans heavily on `is:inline` scripts (theme,
// service-worker registration, favorites/shopping-list state, toasts, …), so a
// blanket `script-src 'self'` would break it and `'unsafe-inline'` would gut
// the policy. Instead we hash every inline script in the built output and pin
// those SHA-256 hashes in `script-src` — no `'unsafe-inline'`, and the hash
// list can never drift from the shipped scripts because it's regenerated from
// them on every build.
//
// Must run AFTER strip-inline-script-comments so the hashes match the exact
// (minified) bytes that ship — register this integration after that one.

// Attribute-less <script>…</script> blocks are exactly the executable inline
// scripts Astro emits from `is:inline` (see strip-inline-script-comments). The
// other script tags in the output are external modules (covered by 'self') or
// non-executable data islands (application/json, application/ld+json), which
// script-src does not gate — so neither needs a hash.
const INLINE_SCRIPT = /<script>([\s\S]*?)<\/script>/g;

async function collectHtmlFiles(dirPath) {
  const entries = await readdir(dirPath, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const full = path.join(dirPath, entry.name);
      if (entry.isDirectory()) return collectHtmlFiles(full);
      return entry.name.endsWith(".html") ? [full] : [];
    }),
  );
  return files.flat();
}

function buildCsp(scriptHashes) {
  const scriptSrc = ["'self'", ...scriptHashes.map((h) => `'sha256-${h}'`)].join(" ");
  return [
    "default-src 'self'",
    "base-uri 'self'",
    "object-src 'none'",
    "frame-ancestors 'none'",
    "form-action 'self'",
    // data: is needed for the tiny inline blur-up placeholders (imagePlaceholder.ts).
    "img-src 'self' data:",
    // Inline <style> blocks and style="" attributes (view transitions, the nav
    // progress bar, etc.) are hashed-per-page and change often, so allow inline
    // styles. Styles are a far weaker XSS vector than scripts.
    "style-src 'self' 'unsafe-inline'",
    `script-src ${scriptSrc}`,
    "font-src 'self'",
    "connect-src 'self'",
    "manifest-src 'self'",
    "worker-src 'self'",
    "frame-src 'none'",
    "upgrade-insecure-requests",
  ].join("; ");
}

export default function securityHeaders() {
  return {
    name: "security-headers",
    hooks: {
      "astro:build:done": async ({ dir, logger }) => {
        const outDir = fileURLToPath(dir);
        const htmlFiles = await collectHtmlFiles(outDir);

        const hashes = new Set();
        for (const file of htmlFiles) {
          const html = await readFile(file, "utf8");
          let match;
          while ((match = INLINE_SCRIPT.exec(html))) {
            hashes.add(createHash("sha256").update(match[1], "utf8").digest("base64"));
          }
        }

        const csp = buildCsp([...hashes].sort());
        // Netlify applies these to every response. HSTS, X-Frame-Options and
        // the Permissions-Policy are static; the CSP carries the inline-script
        // hashes. frame-ancestors already covers clickjacking on modern
        // browsers — X-Frame-Options is the belt-and-braces fallback.
        const headers = `# Generated by integrations/security-headers.mjs on each build — do not edit by hand.
/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  Permissions-Policy: accelerometer=(), autoplay=(), camera=(), display-capture=(), encrypted-media=(), fullscreen=(self), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), usb=(), interest-cohort=()
`;

        await writeFile(path.join(outDir, "_headers"), headers, "utf8");
        logger.info(`wrote _headers with a hash-based CSP (${hashes.size} inline-script hashes)`);
      },
    },
  };
}
